version: 2.1

executors:
  clj:
    docker:
      - image: cimg/clojure:1.11.1-openjdk-17.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS

jobs:

  generate-site:
    executor: clj
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Dependencies
          command: clojure -X:deps prep
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "deps.edn" }}
      - run:
          name: Generate static site
          command: clojure -M:build
      - persist_to_workspace:
          root: public/
          paths:
            - blog/

  deploy:
    docker:
      - image: cimg/deploy:2023.09
    environment:
      REMOTE_HOST: web.monkey-projects.be
    steps:
      - attach_workspace:
          at: public/
      - run:
          name: Create private ssh key file
          command: |
            mkdir -p ~/.ssh
            echo $UPLOAD_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
      - run:
          name: Add host fingerprint to known hosts server
          command: echo "$REMOTE_HOST ssh-ed25519 $HOST_FINGERPRINT" > ~/.ssh/known_hosts
      - run:
          name: Upload to webserver
          command: rsync -mir public/blog/ circleci@$REMOTE_HOST:/var/www/html/blog

workflows:
  version: 2
  deploy-site:
    jobs:
      - generate-site
      - deploy:
          requires:
            - generate-site
          context: deploy-site
